### ISSUE TITLE
Query params still appearing

### ISSUE THREAD

**Issue by AndressAndrade** [gschier/insomnia-plugin-path-parameters#1]
Nice idea for plugin.
At first request, it worked, but then this happened:
![image](https://user-images.githubusercontent.com/8632413/77170918-81002680-6a9a-11ea-8fa1-0acfc871fff0.png)

The plugin was installed:
![image](https://user-images.githubusercontent.com/8632413/77171043-a5f49980-6a9a-11ea-9225-76a57ed4fc98.png)

It started when I tried to request an url with a single path param and no query params, like:
```console
http:my_api/:client
```

My Insomnia version:
![image](https://user-images.githubusercontent.com/8632413/77171522-55ca0700-6a9b-11ea-9d15-df3dd0c3ebbb.png)

**Comment by danarth** [comment]
Hi @AndressAndrade 

Whilst looking at the UI it looks like this plugin is sending query parameters, it actually isn't. By looking at the code in [index.js](https://github.com/gschier/insomnia-plugin-path-parameters/blob/master/index.js). This plugin uses [Insomnia Request/Response Hooks](https://support.insomnia.rest/article/26-plugins#request-response-hooks) in order to replace `:foo` with your variable after a request is sent. The additional query parameters are removed at this point too, so it is no possible that the UI can display this information.

There is an open issue for Insomnia to support the kind of functionality you are describing natively: Kong/insomnia#203

I hope this helps.

**Comment by AndressAndrade** [comment]
Thank you, @DanielArthurUK. I was concerned about the preview URL, but it's just like you said, ones just needs to ignore it.
